-- Inactive shared SQL note.
--
-- This file used to update client Google Ads status in an external database.
-- It is intentionally documentation-only now.
--
-- Reason:
-- Shared cleanup scripts must not mutate databases, client status, or external
-- systems without an explicit operator decision. Client status decisions belong
-- in active client data or an explicitly approved operations workflow, not in
-- a generic shared script.
--
-- Current active workflow:
-- 1. Keep client folders under clients/{agency}/{client}/.
-- 2. Generate Google Ads Editor staging files.
-- 3. Validate with shared/rebuild/staging_validator.py.
-- 4. Keep API upload and external status mutation off.
